### ISSUE TITLE
Write setup documentation

### ISSUE THREAD

**Issue by sidiousvic** [sidiousvic/itzhak#2]
Write documentation in the README for setting up the project, including perhaps script to insert aliases in the shell for operations such as loading data.

- [x] Installing Python
- [x] Installing and configuring virtualenvwrapper properly
- [x] Making and activating a virtual environment via `mkvirtualenv` and `workon` commands from `virtualenvwrapper`
- [x] Installing dependencies
- [x] Using shell_plus
- [x] Creating and loading fixtures

**Comment by numdouglas** [comment]
Documentation guide is done and comprehensible but some of the markdown syntax is not fully translating making some text hard to read.
